# kong/kong.yml
_format_version: "3.0"

services:
  - name: frontend
    url: http://frontend:80
    routes:
      - name: frontend-route
        paths:
          - /
        strip_path: false
        protocols: 
          - http
          - https

  - name: api
    url: http://api:3000
    routes:
      - name: api-route
        paths:
          - /api
        strip_path: true
        protocols:
          - http
          - https
    plugins:
      - name: jwt
        config:
          secret_is_base64: false
          key_claim_name: kid
          claims_to_verify:
            - exp
    connect_timeout: 5000
    write_timeout: 60000
    read_timeout: 60000

  - name: keycloak
    url: http://keycloak:8080
    routes:
      - name: auth-route
        paths:
          - /auth
        strip_path: false
        protocols:
          - http
          - https
    connect_timeout: 5000
    write_timeout: 60000
    read_timeout: 60000

  - name: grafana
    url: http://grafana:3000
    routes:
      - name: grafana-route
        paths:
          - /grafana
        strip_path: true
        protocols:
          - http
          - https
    connect_timeout: 5000
    write_timeout: 60000
    read_timeout: 60000