services:
  kong:
    image: kong:latest
    expose:
      - "8000"  # HTTP
      - "8443"  # HTTPS
      - "8001"  # Admin API
      - "8444"  # Admin API HTTPS
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres  # Use your existing PostgreSQL service name
      KONG_PG_USER: ${POSTGRES_USER:-postgres}
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD}
      KONG_PG_DATABASE: kong  # We'll create this database in your existing PostgreSQL
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_LOG_LEVEL: debug
    volumes:
      - ./config/kong/declarative:/usr/local/kong/declarative:ro
    networks:
      - dive25-net
    depends_on:
      - postgres  # Use your existing PostgreSQL service name
    restart: unless-stopped

  kong-migration:
    image: kong:latest
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres  # Use your existing PostgreSQL service name
      KONG_PG_USER: ${POSTGRES_USER:-postgres}
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD}
      KONG_PG_DATABASE: kong
    depends_on:
      - postgres  # Use your existing PostgreSQL service name
    networks:
      - dive25-net
    restart: on-failure

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --import-realm
      - --log-level=DEBUG
      - --db=postgres
      - --db-url=jdbc:postgresql://postgres:5432/keycloak
      - --db-username=keycloak
      - --db-password=${KEYCLOAK_DB_PASSWORD}
      - --http-enabled=true
      - --http-port=8080
      - --http-relative-path=/auth
      - --proxy-headers=forwarded
      - --hostname-strict=false
      - --health-enabled=true
      - --metrics-enabled=true
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - LDAP_READONLY_PASSWORD=${LDAP_READONLY_PASSWORD}
      - SMTP_USER=${SMTP_USER:-noreply@dive25.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-changeme}
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./config/keycloak/dive25-realm-full.json:/opt/keycloak/data/import/dive25-realm-full.json:ro
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      openldap:
        condition: service_started
    networks:
      - dive25-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health/ready || curl -f http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - METRICS_PORT=9100
      - MONGODB_URI=mongodb://mongodb:27017/dive25
      - REDIS_HOST=redis
      - OPA_URL=http://opa:8181
      - KEYCLOAK_URL=http://keycloak:8080
    ports:
      - "3000:3000"
      - "9100:9100"
    depends_on:
      - mongodb
      - redis
      - opa
      - keycloak
    networks:
      - dive25-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_KEYCLOAK_URL=http://localhost:8080
      - NEXT_PUBLIC_KEYCLOAK_REALM=dive25-realm-full
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=dive25-frontend
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    ports:
      - "3002:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - dive25-net

  mongodb:
    image: mongo:5
    volumes:
      - mongodb_data:/data/db
      - ./config/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - dive25-net

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - dive25-net

  opa:
    image: openpolicyagent/opa:latest-envoy-static
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr=:8181"
    volumes:
      - ./policies:/policies
    networks:
      - dive25-net

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_DB_NAME=keycloak
      - KEYCLOAK_DB_USER=keycloak
      - KEYCLOAK_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres/init-keycloak-db.sh:/docker-entrypoint-initdb.d/init-keycloak-db.sh:ro
      - ./config/postgres/init-users.sql:/docker-entrypoint-initdb.d/init-users.sql:ro
      - ./config/postgres/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql:ro
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - dive25-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

# Update docker-compose.yml to add monitoring services
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - dive25-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - dive25-net

  openldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: "DIVE25"
      LDAP_DOMAIN: "dive25.local"
      LDAP_BASE_DN: "dc=dive25,dc=local"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
      LDAP_CONFIG_PASSWORD: "${LDAP_CONFIG_PASSWORD}"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "${LDAP_READONLY_PASSWORD}"
      LDAP_TLS: "false"
    volumes:
      - ./config/openldap/schema:/bootstrap/schema
      - ./config/openldap/ldif:/bootstrap/ldif
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
    command: --copy-service
    networks:
      - dive25-net

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8444:443"
    depends_on:
      - openldap
    networks:
      - dive25-net

  ldap-exporter:
    build:
      context: ./monitoring/ldap-exporter
      dockerfile: Dockerfile
    environment:
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
    ports:
      - "9330:9330"
    depends_on:
      - openldap
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9330/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dive25-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ${SSL_CERT_PATH:-./certificates/dev/server.crt}:/etc/nginx/ssl/cert.pem:ro
      - ${SSL_KEY_PATH:-./certificates/dev/server.key}:/etc/nginx/ssl/key.pem:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - kong
      - frontend
    networks:
      - dive25-net
    restart: unless-stopped

networks:
  dive25-net:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  postgres_data:
  prometheus_data:
  grafana_data:
  openldap_data:
  openldap_config: