# /monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'

  - job_name: 'api'
    static_configs:
      - targets: ['api:9100']
    metrics_path: '/metrics'

  - job_name: 'keycloak'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['keycloak:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['api:9100']
    metrics_path: '/metrics'

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:9100']

  - job_name: 'openldap'
    static_configs:
      - targets: ['ldap-exporter:9330']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'openldap'

  - job_name: 'ldap-metrics'
    static_configs:
      - targets: ['ldap-exporter:9330']